[variables]
NODE_ENV = "development"

[phases.setup]
nixPkgs = ["nodejs_22", "npm"]

[phases.install]
cmds = ["npm install", "cd frontend && npm install", "cd backend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build", "cd backend && npm run build"]

[start]
cmd = "cd backend && npm start"
